## Упражнения по библиотеке Numpy

In [18]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [5]:
arr = np.random.randint(0, 10, 20)

arr[(arr > 3) & (arr < 8)] *= -1
arr

array([ 9,  9, -6,  0,  3,  2,  2,  1,  3,  2,  0, -7,  9,  1, -5,  1, -6,
       -7,  0, -4])

**2.** Заменить максимальный элемент случайного массива на 0

In [6]:
arr = np.random.randint(1, 10, 10)
print(arr)
arr[arr.argmax()] = 0
print(arr)

[4 5 4 7 1 1 6 4 2 1]
[4 5 4 0 1 1 6 4 2 1]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [7]:
a = np.array([1, 4])
b = np.array([2, 3, 5])
c = np.transpose([np.tile(a, len(b)), np.repeat(b, len(a))])
print(c)

[[1 2]
 [4 2]
 [1 3]
 [4 3]
 [1 5]
 [4 5]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [8]:
a = np.random.randint(0,5,(8,3))
b = np.random.randint(0,5,(2,2))
print(a)
print(b)
c = (a[:,:, np.newaxis, np.newaxis] == b)
rows = (c.sum(axis=(1,2)) >= b.shape[1]).nonzero()[0]
print(rows)

[[1 4 1]
 [0 4 2]
 [4 3 0]
 [3 2 3]
 [0 0 4]
 [3 1 4]
 [0 4 0]
 [2 3 4]]
[[2 2]
 [3 2]]
[1 3 3 7 7]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [9]:
Z = np.random.randint(0,5,(10,3))
E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(Z)
print(U)

[[3 2 1]
 [2 4 2]
 [0 1 3]
 [4 4 2]
 [1 4 0]
 [0 4 1]
 [2 0 1]
 [4 0 3]
 [0 4 1]
 [4 4 4]]
[[3 2 1]
 [2 4 2]
 [0 1 3]
 [4 4 2]
 [1 4 0]
 [0 4 1]
 [2 0 1]
 [4 0 3]
 [0 4 1]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [27]:
a = np.random.randint(0,3,(5,2))
b = np.unique(a, axis=0)
print(a)
print(b)

[[1 1]
 [2 2]
 [2 0]
 [1 0]
 [2 0]]
[[1 0]
 [1 1]
 [2 0]
 [2 2]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [13]:
from functools import reduce

X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])


#NumPy 
D = np.diagonal(X)
print(np.prod(D[D != 0]))


#Default
D = min(len(X), len(X[0]))
print(reduce(lambda a, b : a * b, [X[i][i] for i in range(D) if X[i][i] != 0]))

3
3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [14]:
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])

#NumPy
print(np.in1d(x, y).all())


#Default
print(set(x) == set(y))

True
True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [15]:
x1 = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
x2 = [6, 2, 0, 3, 0, 0, 5, 7, 0]

#NumPy
curr = np.ones((1))
curr = np.hstack((curr, x1))
ind = curr == 0
print(np.max(x1[ind[:-1]]))


#Default
if x2[-1] == 0:
    del x2[-1]
max = x2[x2.index(0)+1]
for i,e in enumerate(x2):
    if e == 0 & max < x2[i+1]:
        max = x2[i+1]
print(max)

5
5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [16]:
x1 = np.array([2, 2, 3, 3, 3, 5, 2, 3, 3, 3, 3])
x2 = [2, 2, 3, 3, 3, 5, 2, 3, 3, 3, 3] 

#NumPy
y = np.hstack((np.ones(1), x1[:- 1]))
first_matches = x1 != y
indexes_1 = np.arange(np.size(x1))[first_matches]
indexes_2 = np.hstack((indexes_1[1:], np.array([np.size(x1)])))
print(x1[first_matches])
print(indexes_2 - indexes_1)


#Default
values = [[x2[0]]]
matches = [1]
i = 0
for value in x2[1:]:
    if value != values[-1][0]:
        matches.append(1)
        i += 1
        values.append([])
        values[i].append(value)
    else:
        values[i].append(value)
        matches[i] += 1
print(list([i[0] for i in values]))
print(matches)

[2 3 5 2 3]
[2 3 1 1 4]
[2, 3, 5, 2, 3]
[2, 3, 1, 1, 4]


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [55]:
import math
import scipy
import time
x = np.array([[1, 0], [2, 0], [3, 0], [4, 4]])
y = np.array([[3, 12], [12, 2], [35, 3], [24, 14]])

#NumPy
start_time = time.time()
print(np.sqrt(np.sum((x[:, np.newaxis] - y) ** 2, axis=-1)))
print("--- %s seconds ---" % (time.time() - start_time))


print('\n')


#Default
start_time = time.time()
result = list()
for i in range(len(x)):
    curr = list()
    for j in range(len(y)):
        dist = 0
        for k in range(len(x[0])):
            dist += (x[i][k] - y[j][k]) ** 2
        curr.append(math.sqrt(dist))
    result.append(curr)
print(result)
print("--- %s seconds ---" % (time.time() - start_time))

print('\n')

#SciPy
start_time = time.time()
print(scipy.spatial.distance.cdist(x,y))
print("--- %s seconds ---" % (time.time() - start_time))

[[12.16552506 11.18033989 34.13209633 26.92582404]
 [12.04159458 10.19803903 33.13608305 26.07680962]
 [12.          9.21954446 32.14031736 25.23885893]
 [ 8.06225775  8.24621125 31.01612484 22.36067977]]
--- 0.0009980201721191406 seconds ---


[[12.165525060596439, 11.180339887498949, 34.132096331752024, 26.92582403567252], [12.041594578792296, 10.198039027185569, 33.13608305156178, 26.076809620810597], [12.0, 9.219544457292887, 32.14031735997639, 25.238858928247925], [8.06225774829855, 8.246211251235321, 31.016124838541646, 22.360679774997898]]
--- 0.0 seconds ---


[[12.16552506 11.18033989 34.13209633 26.92582404]
 [12.04159458 10.19803903 33.13608305 26.07680962]
 [12.          9.21954446 32.14031736 25.23885893]
 [ 8.06225775  8.24621125 31.01612484 22.36067977]]
--- 0.0009963512420654297 seconds ---


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [21]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [25]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [33]:
cm_calories = 60
average_calories = np.mean(calorie_stats)
print(f"Средний калораж - {average_calories}")
print(f"CrunchieMunchies содержат на {abs(cm_calories - average_calories)} калорий меньше чем конкуренты")

Средний калораж - 106.88311688311688
CrunchieMunchies содержат на 46.883116883116884 калорий меньше чем конкуренты


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [35]:
calorie_stats_sorted = np.sort(calorie_stats)
print(calorie_stats_sorted)

[ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [36]:
median_calories = np. median(calorie_stats)
print(median_calories)

110.0


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [52]:
percentile = np.arange(0,101)
nth_percentile = (np.abs((np.percentile(calorie_stats, percentile)) - 60)).argmin()
print(nth_percentile)

3


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [75]:
more_then_cm = np.count_nonzero(np.array(calorie_stats > 60))
more_calories = (more_then_cm * 100) / len(calorie_stats)
print(more_calories)

96.1038961038961


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [77]:
calorie_std = np.std(calorie_stats)
print(calorie_std)
'''
    Аппроксимируя результат(при условии, что выборка была репрезентативна), можно сказать,
    что 95% злаков конкурентов имеют более высокое содержание калорий чем в Mycrunch
'''

19.35718533390827


8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [167]:
'''
Можно сказать что:
    - в злаках CrunchieMunchies содержится на 44.4% меньше калорий (и в пункт со звездочкой отнести "чем в среднем у конкурентов") 
    - CrunchieMunchies менее калорийны чем 95% злаков других производителей   
'''